"""tasting notes: score/occasion/people

Revision ID: a48614711be5
Revises: 7dcba21302a9
Create Date: 2026-09-07 01:13:10.443756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48614711be5'
down_revision = '7dcba21302a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasting_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('occasion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('people', sa.String(length=255), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasting_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('people')
        batch_op.drop_column('occasion')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
