"""AI wine research fields, Telegram linking

Revision ID: fc6ce5e74b62
Revises: 306b85f22b58
Create Date: 2026-09-08 11:01:49.425381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6ce5e74b62'
down_revision = '306b85f22b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_code_expires', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['telegram_chat_id'])

    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_price', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tasting_profile', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('researched_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.drop_column('researched_at')
        batch_op.drop_column('tasting_profile')
        batch_op.drop_column('estimated_price')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('telegram_link_code_expires')
        batch_op.drop_column('telegram_link_code')
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
